import path from 'path';
import { writeFile, ensureDir } from '../utils/index.js';
import { createSpinner, spinnerSuccess, spinnerError } from '../ui/spinner.js';

/**
 * Generate Synapse "nuclear" folder structure for a slice
 * 
 * nuclear/
 *   └── {sliceName}/
 *       ├── index.ts      - Main exports
 *       ├── types.ts      - TypeScript types
 *       ├── const.ts      - Constants
 *       ├── actions.ts    - Synapse actions
 *       ├── selectors.ts  - State selectors
 *       └── hooks.ts      - Custom hooks
 */
export const generateSynapseNuclear = async (
  projectDir: string,
  sliceName: string,
  basePath?: string
): Promise<void> => {
  const spinner = createSpinner(`Creating Synapse nuclear slice: ${sliceName}...`);
  spinner.start();

  try {
    const nuclearDir = path.join(
      projectDir,
      basePath || 'src',
      'nuclear',
      sliceName
    );

    await ensureDir(nuclearDir);

    // Capitalize first letter for type names
    const typeName = sliceName.charAt(0).toUpperCase() + sliceName.slice(1);

    // types.ts
    const typesContent = `/**
 * ${typeName} Types
 * Auto-generated by Forge CLI
 */

export interface ${typeName}State {
  items: ${typeName}Item[];
  selectedId: string | null;
  isLoading: boolean;
  error: string | null;
}

export interface ${typeName}Item {
  id: string;
  // Add your item properties here
}

export type ${typeName}Action =
  | { type: '${sliceName.toUpperCase()}_SET_ITEMS'; payload: ${typeName}Item[] }
  | { type: '${sliceName.toUpperCase()}_ADD_ITEM'; payload: ${typeName}Item }
  | { type: '${sliceName.toUpperCase()}_UPDATE_ITEM'; payload: ${typeName}Item }
  | { type: '${sliceName.toUpperCase()}_DELETE_ITEM'; payload: string }
  | { type: '${sliceName.toUpperCase()}_SELECT'; payload: string | null }
  | { type: '${sliceName.toUpperCase()}_SET_LOADING'; payload: boolean }
  | { type: '${sliceName.toUpperCase()}_SET_ERROR'; payload: string | null };
`;

    await writeFile(path.join(nuclearDir, 'types.ts'), typesContent);

    // const.ts
    const constContent = `/**
 * ${typeName} Constants
 * Auto-generated by Forge CLI
 */

export const ${sliceName.toUpperCase()}_ACTION_TYPES = {
  SET_ITEMS: '${sliceName.toUpperCase()}_SET_ITEMS',
  ADD_ITEM: '${sliceName.toUpperCase()}_ADD_ITEM',
  UPDATE_ITEM: '${sliceName.toUpperCase()}_UPDATE_ITEM',
  DELETE_ITEM: '${sliceName.toUpperCase()}_DELETE_ITEM',
  SELECT: '${sliceName.toUpperCase()}_SELECT',
  SET_LOADING: '${sliceName.toUpperCase()}_SET_LOADING',
  SET_ERROR: '${sliceName.toUpperCase()}_SET_ERROR',
} as const;

export const ${sliceName.toUpperCase()}_INITIAL_STATE = {
  items: [],
  selectedId: null,
  isLoading: false,
  error: null,
} as const;

export const ${sliceName.toUpperCase()}_STORAGE_KEY = '${sliceName}_state';
`;

    await writeFile(path.join(nuclearDir, 'const.ts'), constContent);

    // actions.ts
    const actionsContent = `/**
 * ${typeName} Actions
 * Auto-generated by Forge CLI
 */

import { ${sliceName.toUpperCase()}_ACTION_TYPES } from './const.js';
import type { ${typeName}Item, ${typeName}Action } from './types.js';

export const ${sliceName}Actions = {
  setItems: (items: ${typeName}Item[]): ${typeName}Action => ({
    type: ${sliceName.toUpperCase()}_ACTION_TYPES.SET_ITEMS,
    payload: items,
  }),

  addItem: (item: ${typeName}Item): ${typeName}Action => ({
    type: ${sliceName.toUpperCase()}_ACTION_TYPES.ADD_ITEM,
    payload: item,
  }),

  updateItem: (item: ${typeName}Item): ${typeName}Action => ({
    type: ${sliceName.toUpperCase()}_ACTION_TYPES.UPDATE_ITEM,
    payload: item,
  }),

  deleteItem: (id: string): ${typeName}Action => ({
    type: ${sliceName.toUpperCase()}_ACTION_TYPES.DELETE_ITEM,
    payload: id,
  }),

  select: (id: string | null): ${typeName}Action => ({
    type: ${sliceName.toUpperCase()}_ACTION_TYPES.SELECT,
    payload: id,
  }),

  setLoading: (isLoading: boolean): ${typeName}Action => ({
    type: ${sliceName.toUpperCase()}_ACTION_TYPES.SET_LOADING,
    payload: isLoading,
  }),

  setError: (error: string | null): ${typeName}Action => ({
    type: ${sliceName.toUpperCase()}_ACTION_TYPES.SET_ERROR,
    payload: error,
  }),
};
`;

    await writeFile(path.join(nuclearDir, 'actions.ts'), actionsContent);

    // selectors.ts
    const selectorsContent = `/**
 * ${typeName} Selectors
 * Auto-generated by Forge CLI
 */

import type { ${typeName}State, ${typeName}Item } from './types.js';

// Assuming root state has a ${sliceName} key
type RootState = { ${sliceName}: ${typeName}State };

export const ${sliceName}Selectors = {
  getState: (state: RootState): ${typeName}State => state.${sliceName},

  getItems: (state: RootState): ${typeName}Item[] => state.${sliceName}.items,

  getSelectedId: (state: RootState): string | null => state.${sliceName}.selectedId,

  getSelectedItem: (state: RootState): ${typeName}Item | undefined => {
    const { items, selectedId } = state.${sliceName};
    return items.find((item) => item.id === selectedId);
  },

  getById: (state: RootState, id: string): ${typeName}Item | undefined => {
    return state.${sliceName}.items.find((item) => item.id === id);
  },

  getIsLoading: (state: RootState): boolean => state.${sliceName}.isLoading,

  getError: (state: RootState): string | null => state.${sliceName}.error,

  getCount: (state: RootState): number => state.${sliceName}.items.length,

  isEmpty: (state: RootState): boolean => state.${sliceName}.items.length === 0,
};
`;

    await writeFile(path.join(nuclearDir, 'selectors.ts'), selectorsContent);

    // hooks.ts
    const hooksContent = `/**
 * ${typeName} Hooks
 * Auto-generated by Forge CLI
 */

import { useCallback, useMemo } from 'react';
// import { useSynapse } from '@forgedevstack/synapse';
import { ${sliceName}Actions } from './actions.js';
import { ${sliceName}Selectors } from './selectors.js';
import type { ${typeName}Item } from './types.js';

/**
 * Hook for ${sliceName} state and actions
 * 
 * TODO: Uncomment and integrate with your Synapse store
 */
export const use${typeName} = () => {
  // const { state, dispatch } = useSynapse();
  
  // Temporary mock - replace with actual Synapse integration
  const state = { ${sliceName}: { items: [], selectedId: null, isLoading: false, error: null } };
  const dispatch = (action: unknown) => console.log('Dispatch:', action);

  const items = useMemo(
    () => ${sliceName}Selectors.getItems(state),
    [state]
  );

  const selectedItem = useMemo(
    () => ${sliceName}Selectors.getSelectedItem(state),
    [state]
  );

  const isLoading = ${sliceName}Selectors.getIsLoading(state);
  const error = ${sliceName}Selectors.getError(state);

  const addItem = useCallback(
    (item: ${typeName}Item) => dispatch(${sliceName}Actions.addItem(item)),
    [dispatch]
  );

  const updateItem = useCallback(
    (item: ${typeName}Item) => dispatch(${sliceName}Actions.updateItem(item)),
    [dispatch]
  );

  const deleteItem = useCallback(
    (id: string) => dispatch(${sliceName}Actions.deleteItem(id)),
    [dispatch]
  );

  const selectItem = useCallback(
    (id: string | null) => dispatch(${sliceName}Actions.select(id)),
    [dispatch]
  );

  return {
    // State
    items,
    selectedItem,
    isLoading,
    error,
    count: items.length,
    isEmpty: items.length === 0,

    // Actions
    addItem,
    updateItem,
    deleteItem,
    selectItem,
    setLoading: (loading: boolean) => dispatch(${sliceName}Actions.setLoading(loading)),
    setError: (err: string | null) => dispatch(${sliceName}Actions.setError(err)),
  };
};
`;

    await writeFile(path.join(nuclearDir, 'hooks.ts'), hooksContent);

    // index.ts - main exports
    const indexContent = `/**
 * ${typeName} Nuclear Slice
 * Auto-generated by Forge CLI
 * 
 * Usage:
 *   import { ${sliceName}Actions, ${sliceName}Selectors, use${typeName} } from './nuclear/${sliceName}';
 */

export * from './types.js';
export * from './const.js';
export * from './actions.js';
export * from './selectors.js';
export * from './hooks.js';
`;

    await writeFile(path.join(nuclearDir, 'index.ts'), indexContent);

    spinnerSuccess(spinner, `Nuclear slice "${sliceName}" created at ${nuclearDir}`);
  } catch (error) {
    spinnerError(spinner, `Failed to create nuclear slice: ${error}`);
    throw error;
  }
};
