import path from 'path';
import chalk from 'chalk';
import enquirer from 'enquirer';
const { prompt } = enquirer;
import { printSmallLogo, printSuccess } from '../ui/logo.js';
import { createSpinner, spinnerSuccess, spinnerError } from '../ui/spinner.js';
import { COLORS } from '../ui/colors.js';
import {
  pathExists,
  addPackages,
  ensureDir,
  writeFile,
} from '../utils/index.js';
import type { PackageManager } from '../ui/prompts.js';
import { generateSynapseNuclear } from '../templates/synapse.js';

const FORGE_PACKAGES = {
  bear: '@forgedevstack/bear@^1.0.9',
  'grid-table': '@forgedevstack/grid-table',
  'forge-query': '@forgedevstack/forge-query',
  'forge-form': '@forgedevstack/forge-form',
  'forge-compass': '@forgedevstack/forge-compass',
  synapse: '@forgedevstack/synapse',
  anvil: '@forgedevstack/anvil',
  harbor: '@forgedevstack/harbor',
  kiln: '@forgedevstack/kiln',
  relay: '@forgedevstack/relay',
  'forge-auth': '@forgedevstack/forge-auth',
  crucible: '@forgedevstack/crucible',
} as const;

type ForgePackage = keyof typeof FORGE_PACKAGES;

type CrucibleScope = 'both' | 'client' | 'server';

interface AddOptions {
  color?: string;
  nuclear?: string;
  scope?: CrucibleScope;
}

const detectPackageManager = async (cwd: string): Promise<PackageManager> => {
  if (await pathExists(path.join(cwd, 'bun.lockb'))) return 'bun';
  if (await pathExists(path.join(cwd, 'pnpm-lock.yaml'))) return 'pnpm';
  if (await pathExists(path.join(cwd, 'yarn.lock'))) return 'yarn';
  return 'npm';
};

const CRUCIBLE_CONFIG_HEADER = `// Crucible Testing Configuration
// Generated by Forge CLI
// https://forgedevstack.com/crucible
`;

const generateCrucibleConfig = (scope: CrucibleScope): string => {
  const clientImports = `render, cleanup, renderHook, fireEvent, waitFor, act`;
  const serverImports = `request, assertResponse, createMockServer, configureRoutes`;
  const coreImports = `describe, it, test, expect, spy, spyOn, beforeAll, afterAll, beforeEach, afterEach, configure, run`;

  if (scope === 'client') {
    return `${CRUCIBLE_CONFIG_HEADER}
// Core
export { ${coreImports} } from '@forgedevstack/crucible';

// Client (React Testing)
export { ${clientImports} } from '@forgedevstack/crucible/client';
`;
  }

  if (scope === 'server') {
    return `${CRUCIBLE_CONFIG_HEADER}
// Core
export { ${coreImports} } from '@forgedevstack/crucible';

// Server (API Testing)
export { ${serverImports} } from '@forgedevstack/crucible/server';
`;
  }

  // both
  return `${CRUCIBLE_CONFIG_HEADER}
// Core
export { ${coreImports} } from '@forgedevstack/crucible';

// Client (React Testing)
export { ${clientImports} } from '@forgedevstack/crucible/client';

// Server (API Testing)
export { ${serverImports} } from '@forgedevstack/crucible/server';
`;
};

const generateExampleTest = (scope: CrucibleScope): string => {
  if (scope === 'server') {
    return `import { describe, it, expect } from '@forgedevstack/crucible';
import { request, assertResponse, createMockServer } from '@forgedevstack/crucible/server';

describe('API Tests', () => {
  const server = createMockServer({
    routes: [
      { method: 'GET', path: '/api/health', body: { status: 'ok' } },
    ],
  });

  beforeAll(async () => { await server.start(); });
  afterAll(async () => { await server.stop(); });

  it('health check returns 200', async () => {
    const res = await request.get('/api/health');
    assertResponse(res).toHaveStatus(200).and.toHaveBody({ status: 'ok' });
  });
});
`;
  }

  if (scope === 'client') {
    return `import { describe, it, expect } from '@forgedevstack/crucible';
import { render, fireEvent } from '@forgedevstack/crucible/client';

describe('Component Tests', () => {
  it('renders and responds to interaction', () => {
    // const { getByText, getByRole } = render(<MyComponent />);
    // fireEvent.click(getByRole('button'));
    // expect(getByText('Clicked!')).toBeDefined();
    expect(true).toBeTruthy();
  });
});
`;
  }

  // both
  return `import { describe, it, expect, configure, run } from '@forgedevstack/crucible';

// Client imports
// import { render, fireEvent } from '@forgedevstack/crucible/client';

// Server imports
// import { request, assertResponse, createMockServer } from '@forgedevstack/crucible/server';

configure({ verbose: true, colors: true });

describe('Example Test Suite', () => {
  it('passes a basic assertion', () => {
    expect(1 + 1).toBe(2);
    expect('ForgeStack').toContain('Forge');
    expect({ name: 'Crucible' }).toHaveProperty('name', 'Crucible');
  });
});

// Uncomment to run:
// run().then((result) => console.log(result));
`;
};

export const addCommand = async (
  packageName?: string,
  options: AddOptions = {}
): Promise<void> => {
  printSmallLogo();

  const cwd = process.cwd();

  // Check if we're in a project
  if (!(await pathExists(path.join(cwd, 'package.json')))) {
    console.log(chalk.hex(COLORS.error)('\n  Error: No package.json found. Run this in a project directory.\n'));
    process.exit(1);
  }

  // Detect package manager
  const pm = await detectPackageManager(cwd);

  // If no package specified, show interactive menu
  let pkg: ForgePackage;
  if (!packageName || !(packageName in FORGE_PACKAGES)) {
    const pink = chalk.hex(COLORS.primary);
    const accent = chalk.hex(COLORS.accent);
    const muted = chalk.hex(COLORS.muted);

    const response = await prompt<{ package: ForgePackage }>({
      type: 'select',
      name: 'package',
      message: pink('Which ForgeStack package to add?'),
      choices: [
        { name: 'bear' as const, message: `${accent('🐻 Bear UI')} ${muted('- Component library')}` },
        { name: 'grid-table' as const, message: `${accent('📊 Grid Table')} ${muted('- Data grid')}` },
        { name: 'forge-query' as const, message: `${accent('🔍 Forge Query')} ${muted('- Data fetching')}` },
        { name: 'forge-form' as const, message: `${accent('📝 Forge Form')} ${muted('- Form management')}` },
        { name: 'forge-compass' as const, message: `${accent('🧭 Forge Compass')} ${muted('- Routing')}` },
        { name: 'synapse' as const, message: `${accent('⚡ Synapse')} ${muted('- State management')}` },
        { name: 'anvil' as const, message: `${accent('🔨 Anvil')} ${muted('- Utilities & hooks')}` },
        { name: 'harbor' as const, message: `${accent('⚓ Harbor')} ${muted('- API server')}` },
        { name: 'kiln' as const, message: `${accent('🏗️  Kiln')} ${muted('- Build tools')}` },
        { name: 'relay' as const, message: `${accent('📡 Relay')} ${muted('- HTTP client')}` },
        { name: 'forge-auth' as const, message: `${accent('🔐 Forge Auth')} ${muted('- Authentication')}` },
        { name: 'crucible' as const, message: `${accent('🔥 Crucible')} ${muted('- Testing (FE + BE)')}` },
      ],
    });
    pkg = response.package;
  } else {
    pkg = packageName as ForgePackage;
  }

  const packageToInstall = FORGE_PACKAGES[pkg];

  // ─── Crucible: ask for scope ─────────────────────────────────
  let crucibleScope: CrucibleScope = 'both';
  if (pkg === 'crucible') {
    const pink = chalk.hex(COLORS.primary);
    const accent = chalk.hex(COLORS.accent);
    const muted = chalk.hex(COLORS.muted);

    if (!options.scope) {
      const scopeResponse = await prompt<{ scope: CrucibleScope }>({
        type: 'select',
        name: 'scope',
        message: pink('What will you test with Crucible?'),
        choices: [
          { name: 'both' as const, message: `${accent('🔥 Both')} ${muted('- Frontend (React) + Backend (API)')}` },
          { name: 'client' as const, message: `${accent('⚛️  Frontend')} ${muted('- React components, hooks, DOM')}` },
          { name: 'server' as const, message: `${accent('🖥️  Backend')} ${muted('- API routes, mock server, auth')}` },
        ],
      });
      crucibleScope = scopeResponse.scope;
    } else {
      crucibleScope = options.scope;
    }
  }

  // Install the package
  const spinner = createSpinner(`Installing ${pkg}...`);
  spinner.start();

  try {
    await addPackages(pm, [packageToInstall], cwd);
    spinnerSuccess(spinner, `${pkg} installed successfully`);
  } catch {
    spinnerError(spinner, `Failed to install ${pkg}`);
    process.exit(1);
  }

  // ─── Special: Bear theme config ──────────────────────────────
  if (pkg === 'bear' && options.color) {
    const themeSpinner = createSpinner('Creating Bear theme config...');
    themeSpinner.start();

    try {
      const themeConfig = `// Bear UI Theme Configuration
// Generated by Forge CLI

export const bearTheme = {
  colors: {
    primary: '${options.color}',
  },
};
`;
      await writeFile(path.join(cwd, 'src', 'theme', 'bear.config.ts'), themeConfig);
      spinnerSuccess(themeSpinner, 'Theme config created at src/theme/bear.config.ts');
    } catch {
      spinnerError(themeSpinner, 'Failed to create theme config');
    }
  }

  // ─── Special: Synapse nuclear slice ──────────────────────────
  if (pkg === 'synapse' && options.nuclear) {
    await generateSynapseNuclear(cwd, options.nuclear);
  }

  // ─── Special: Crucible test setup ────────────────────────────
  if (pkg === 'crucible') {
    const configSpinner = createSpinner('Setting up Crucible testing...');
    configSpinner.start();

    try {
      // Create test directory
      const testDir = path.join(cwd, 'src', '__tests__');
      await ensureDir(testDir);

      // Write crucible config (re-exports based on scope)
      const configPath = path.join(testDir, 'crucible.setup.ts');
      await writeFile(configPath, generateCrucibleConfig(crucibleScope));

      // Write example test
      const examplePath = path.join(testDir, 'example.test.ts');
      await writeFile(examplePath, generateExampleTest(crucibleScope));

      const scopeLabel =
        crucibleScope === 'both' ? 'Frontend + Backend' :
        crucibleScope === 'client' ? 'Frontend (React)' :
        'Backend (API)';

      spinnerSuccess(configSpinner, `Crucible configured for ${scopeLabel}`);

      const muted = chalk.hex(COLORS.muted);
      const accent = chalk.hex(COLORS.accent);
      console.log();
      console.log(muted('  Files created:'));
      console.log(`  ${accent('→')} src/__tests__/crucible.setup.ts`);
      console.log(`  ${accent('→')} src/__tests__/example.test.ts`);
      console.log();
      console.log(muted('  Add to package.json scripts:'));
      console.log(`  ${accent('"test": "tsx src/__tests__/example.test.ts"')}`);
    } catch {
      spinnerError(configSpinner, 'Failed to create Crucible config');
    }
  }

  console.log();
  printSuccess(`${pkg} added to your project!`);
  console.log();
};
