import path from 'path';
import chalk from 'chalk';
import enquirer from 'enquirer';
const { prompt } = enquirer;
import { printSmallLogo, printSuccess } from '../ui/logo.js';
import { createSpinner, spinnerSuccess, spinnerError } from '../ui/spinner.js';
import { COLORS } from '../ui/colors.js';
import {
  pathExists,
  addPackages,
  ensureDir,
  writeFile,
} from '../utils/index.js';
import type { PackageManager } from '../ui/prompts.js';
import { generateSynapseNuclear } from '../templates/synapse.js';

const FORGE_PACKAGES = {
  bear: '@forgedevstack/bear@^1.0.7',
  'grid-table': '@forgedevstack/grid-table',
  'forge-query': '@forgedevstack/forge-query',
  'forge-form': '@forgedevstack/forge-form',
  'forge-compass': '@forgedevstack/forge-compass',
  synapse: '@forgedevstack/synapse',
  anvil: '@forgedevstack/anvil',
  harbor: '@forgedevstack/harbor',
  kiln: '@forgedevstack/kiln',
} as const;

type ForgePackage = keyof typeof FORGE_PACKAGES;

interface AddOptions {
  color?: string;
  nuclear?: string;
}

const detectPackageManager = async (cwd: string): Promise<PackageManager> => {
  if (await pathExists(path.join(cwd, 'bun.lockb'))) return 'bun';
  if (await pathExists(path.join(cwd, 'pnpm-lock.yaml'))) return 'pnpm';
  if (await pathExists(path.join(cwd, 'yarn.lock'))) return 'yarn';
  return 'npm';
};

export const addCommand = async (
  packageName?: string,
  options: AddOptions = {}
): Promise<void> => {
  printSmallLogo();

  const cwd = process.cwd();

  // Check if we're in a project
  if (!(await pathExists(path.join(cwd, 'package.json')))) {
    console.log(chalk.hex(COLORS.error)('\n  Error: No package.json found. Run this in a project directory.\n'));
    process.exit(1);
  }

  // Detect package manager
  const pm = await detectPackageManager(cwd);

  // If no package specified, show interactive menu
  let pkg: ForgePackage;
  if (!packageName || !(packageName in FORGE_PACKAGES)) {
    const pink = chalk.hex(COLORS.primary);
    const accent = chalk.hex(COLORS.accent);
    const muted = chalk.hex(COLORS.muted);

    const response = await prompt<{ package: ForgePackage }>({
      type: 'select',
      name: 'package',
      message: pink('Which ForgeStack package to add?'),
      choices: [
        { name: 'bear' as const, message: `${accent('🐻 Bear UI')} ${muted('- Component library')}` },
        { name: 'grid-table' as const, message: `${accent('📊 Grid Table')} ${muted('- Data grid')}` },
        { name: 'forge-query' as const, message: `${accent('🔍 Forge Query')} ${muted('- Data fetching')}` },
        { name: 'forge-form' as const, message: `${accent('📝 Forge Form')} ${muted('- Form management')}` },
        { name: 'forge-compass' as const, message: `${accent('🧭 Forge Compass')} ${muted('- Routing')}` },
        { name: 'synapse' as const, message: `${accent('⚡ Synapse')} ${muted('- State management')}` },
        { name: 'anvil' as const, message: `${accent('🔨 Anvil')} ${muted('- Utilities & hooks')}` },
        { name: 'harbor' as const, message: `${accent('⚓ Harbor')} ${muted('- API client')}` },
        { name: 'kiln' as const, message: `${accent('🔥 Kiln')} ${muted('- Build tools')}` },
      ],
    });
    pkg = response.package;
  } else {
    pkg = packageName as ForgePackage;
  }

  const packageToInstall = FORGE_PACKAGES[pkg];

  // Install the package
  const spinner = createSpinner(`Installing ${pkg}...`);
  spinner.start();

  try {
    await addPackages(pm, [packageToInstall], cwd);
    spinnerSuccess(spinner, `${pkg} installed successfully`);
  } catch {
    spinnerError(spinner, `Failed to install ${pkg}`);
    process.exit(1);
  }

  // Special handling for Bear - create theme config
  if (pkg === 'bear' && options.color) {
    const themeSpinner = createSpinner('Creating Bear theme config...');
    themeSpinner.start();

    try {
      const themeConfig = `// Bear UI Theme Configuration
// Generated by Forge CLI

export const bearTheme = {
  colors: {
    primary: '${options.color}',
  },
};
`;
      await writeFile(path.join(cwd, 'src', 'theme', 'bear.config.ts'), themeConfig);
      spinnerSuccess(themeSpinner, 'Theme config created at src/theme/bear.config.ts');
    } catch {
      spinnerError(themeSpinner, 'Failed to create theme config');
    }
  }

  // Special handling for Synapse - create nuclear structure
  if (pkg === 'synapse' && options.nuclear) {
    await generateSynapseNuclear(cwd, options.nuclear);
  }

  console.log();
  printSuccess(`${pkg} added to your project!`);
  console.log();
};
